= Java Enums Generator
Paulo Jerônimo <paulojeronimo@gmail.com>, {localdatetime}
:toc:
:icons: font

== About

This project can be used by you to generate some https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html[Java Enums^].

These enums are generated by a https://groovy-lang.org/structure.html#_scripts_versus_classes[Groovy script^]
called link:java-enums-generator.groovy[] that reads a configuration file named `config.groovy`
with has a sample (link:config.sample.groovy[]) that you can you a base.

== Motivation

=== One

Java programmers don't like to waste their time writing enums.
Especially if these enums are big and their data comes from a database.
You can search for projects with this intention and you will find things like these:

* https://github.com/dfsisinni/enum-generator-from-csv-java
* https://github.com/translocathor/enumeration-generator

So, for example, as a programmer, you have a challenge to create two (2) separated Java enums
to represent the https://en.wikipedia.org/wiki/States_of_Brazil[Brazilian states and regions^].
Obviously, you can create a Java enum to Brazilian regions by your hands
with minimal effort because there are only five (5) regions in Brazil.
But, things come annoying when you want to create a Java Enum to the Brazilian states cause
there are 26 states plus one federal district.
And, you want to link each state in its enum with the corresponding region enum.

You think that you go through this problem only one time and it's ok to write theses Java enums by hand
because they are almost immutable (changes almost never happen).
But, your boss wants that you do the same, again, for the American states ... +
Hahaha 😄! You will lose your time again!

A better solution to this problem is to build your Java enums from existing and officially APIs (made by government institutions).
A Brazilian institution called https://www.ibge.gov.br/cidades-e-estados[IBGE^]
provide two URLs that we use in link:config.sample.groovy[our configuration example^]
to get the regions and states:

* https://servicodados.ibge.gov.br/api/v1/localidades/regioes
* https://servicodados.ibge.gov.br/api/v1/localidades/estados

Based on the response of these APIs and the configuration written in a https://groovy-lang.org/semantics.html[Groovy semantics^]
we can build our Java enums in a smart way as you will see through the code of this project.

=== Two

A personal motivation:
I wanted to improve my skills in https://groovy-lang.org[Groovy programming language^] by exploring it more.

Actually, today I could produce the same results gained here by using my current knowledge in https://www.python.org/[Python^] and https://jinja.palletsprojects.com/en/2.11.x/[Jinja^] or even using my recent skills in https://dhall-lang.org/[Dhall^].
Later, my goal is to produce some posts by comparing this solution with others that I will produce with these alternatives.

== Alternative ways to execute this project

Any of the following alternatives will build some Java enums inside your
current directory.

Try the following commands and you will get a bunch of Java code inside a directory tree `com/example/JavaProject/enums`.

=== If you have Groovy installed and have cloned this project

----
$ groovy java-enums-generator.groovy
Generating output in directory "sample.test/src/main/java" ...
Creating enum com.example.JavaProject.enums.BRRegion ...
Creating interface com.example.JavaProject.enums.Region ...
Creating enum com.example.JavaProject.enums.BRState ...
Creating interface com.example.JavaProject.enums.State ...
----

You can see and compile the generated Java classes with the following commands:

----
$ tree sample.test
sample.test
`-- src
    `-- main
        `-- java
            `-- com
                `-- example
                    `-- JavaProject
                        `-- enums
                            |-- BRRegion.java
                            |-- BRState.java
                            |-- Region.java
                            `-- State.java

7 directories, 4 files
----

----
$ (cd sample.test/src/main/java && javac com/example/JavaProject/enums/*.java)
----

=== If you have Docker installed

----
$ docker run -it -v "$PWD":/mnt paulojeronimo/java-enums-generator
----

WARNING: This does not exist yet. It will be available in the next git commits.

== Configuration

Your configuration of the generated Java enums needs to be written in Groovy
in a file called `config.groovy` or the file `config.sample.groovy` will be used.
After writing it, you can validate its contents by running the following script:

----
$ groovy config.test.groovy
Testing "config.sample.groovy" filled with a content sample ...
Configuration should define a map of properties ... ok!
Configuration should have a keySet equals to [package_name, set] ... ok!
Configuration should have at least one set ... ok!
----
